### ISSUE TITLE
D's `function` type is a function pointer

### ISSUE THREAD

**Issue by araspik** [opisano/readline#1]
I believe that `rl_bind_key` and related functions accept a function pointer. The problem is that in D `int function(int, int)` (which is what `rl_bind_key` accepts) is _already_ a function pointer. You are making it accept a pointer to a function pointer, which I do not think is what you want. It's not what happens on the `libreadline` tutorial in C either.

**Comment by opisano** [comment]
Hello,

Sorry for the late answer, I have been quite busy this week. 
I understand that there is an extra level of indirection in the rl_* functions that should not be. I will update the package ASAP.

Thank you

**Comment by opisano** [comment]
Fixed in package version 0.2.0. 
Thank you for reporting this issue.
